# Generated by Django 3.2.8 on 2021-12-06 17:07

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_post_favourites'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodbank',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contents.post')),
                ('pincode', models.IntegerField(max_length=6)),
            ],
            bases=('contents.post',),
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
