# Generated by Django 3.2.8 on 2021-12-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20211206_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='blooddonors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('blood_group', models.CharField(max_length=10)),
                ('contact', models.IntegerField(default=0)),
                ('home_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
