# Generated by Django 3.2.8 on 2021-12-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_auto_20211230_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonors',
            name='contact',
            field=models.CharField(max_length=40),
        ),
    ]
